### PR TITLE
Enable testing with Travis-CI

### PR DESCRIPTION
**Pull request by jemc**
This commit adds support for testing with Travis-CI, so we can know when the build is broken or the tests are failing.
It will still need to be switched on for your account at https://travis-ci.org

I branched it from #11 because the tests were failing prior to the commit in that PR.

### CODE REVIEW

**Comment by mattn** [comment]
I'm asking mruby/mruby about this.

https://github.com/mruby/mruby/pull/2723

**Comment by zzak** [comment]
@mattn Any resolution?

**Comment by mattn** [comment]
I'll cherry-pick second commit.

**Comment by mattn** [comment]
Merged https://github.com/mattn/mruby-json/commit/fe769741251a3846be6e637d0af5deddd8fa0de3

Thank you.

**Comment by mattn** [comment]
YAY https://travis-ci.org/mattn/mruby-json/builds/70683978

**Comment by zzak** [comment]
@mattn thank you!

**Pull request closed without merging**
