### PR TITLE
Fix test failure on mruby-2.0.1.

### PR DESCRIPTION
**Pull request by Shokuji**

### CODE REVIEW

**Comment by mattn** [comment]
What did you get with test?

**Comment by Shokuji** [comment]
The test was corrected because the specification of to_s changed in the version upgrade of mruby.

**Comment by take-cheeze** [comment]
👎 Since test data shouldn't be changed because of mruby changes.
Instead this line needs to be specialized for float.
https://github.com/mattn/mruby-json/blob/054699892b0d681110e7348440cddb70a3fd671e/src/mrb_json.c#L72

**Comment by katzer** [comment]
> Since test data shouldn't be changed because of mruby changes.

I agree, but isn't it incorrect that `JSON.stringify({true=> 5.0})` returns `'{"true":5}'`. The right result should be `'{"true":5.0}'`

**Comment by take-cheeze** [comment]
Sometimes mruby promotes overflowed integer to float so I feel `{"true":5}` should be kept.

**Comment by mattn** [comment]
The commit was reverted https://github.com/mruby/mruby/commit/9d08025b8b0fc9828120d48c61bde9c4ba49ce74

So closable?

**Comment by mattn** [comment]
Removed the test.

**Pull request closed without merging**
